steps:
  - label: 'Triggering pipelines'
    plugins:
      - chronotc/monorepo-diff#v2.3.0:
          diff: .buildkite/diff-exclude-md-files.sh
          watch:
            - path: .buildkite/get-path.sh
              config:
                command: 'echo deploy-bar'
            - path: '**/*.md'
              config:
                command: 'echo skip-pr'
