steps:
  - label: 'Triggering pipelines'
    plugins:
      - chronotc/monorepo-diff#v2.3.0:
          diff: .buildkite/diff-exclude-md-files.sh
          watch:
            config:
              command: 'echo deploy-bar'
